name: Build

on: [push, pull_request]

jobs:
  build-overlays:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: "oracle"
          java-version: "17"

      - name: Create
        run: ./create.sh

      - uses: actions/upload-artifact@v4
        with:
          name: magisk-module
          path: module/

      - uses: actions/upload-artifact@v4
        with:
          name: apks
          path: apks/
